version: '3'
services:
  localstack:
    image: localstack/localstack:1.3.1
    ports:
      # Ext services port range
      - "4510-4559:4510-4559"
      # LocalStack Gateway
      - "4566:4566"
    environment:
      - SERVICES=sns,sqs,ses
      - EAGER_SERVICE_LOADING=1 # Needed, otherwise SERVICES is ignored
      - AWS_ACCESS_KEY_ID=34gasdf3
      - AWS_SECRET_KEY=432fgasd
      - DEBUG=1

  mongodb:
    image: mongo:5.0.9
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: gb-poa-publishing
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: super
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: super
    depends_on:
      - mongodb

volumes:
  mongodb_data: